# Generated by Django 4.0.2 on 2022-02-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMORPG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('T', 'Tanks'), ('H', 'Hills'), ('D', 'Dealer'), ('GM', 'Gildmaster'), ('QG', 'Questgiver'), ('SM', 'Smith'), ('L', 'Leathers'), ('PM', 'Poisonmaker'), ('SM', 'Spellmaster')], max_length=2),
        ),
    ]
