# Generated by Django 4.0.2 on 2022-03-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMORPG', '0005_alter_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
